/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalexamproject;

/**
 *
 * @author Al
 */
public class AssignmentForm extends javax.swing.JFrame {

    /**
     * Creates new form AssignmentForm
     */
    public AssignmentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mHome = new javax.swing.JMenu();
        mEmployees = new javax.swing.JMenu();
        mDepartments = new javax.swing.JMenu();
        mAssignments = new javax.swing.JMenu();
        mPayroll = new javax.swing.JMenu();
        mClose = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Assignment");

        jMenuBar1.setBackground(new java.awt.Color(51, 0, 204));
        jMenuBar1.setForeground(new java.awt.Color(255, 153, 153));

        mHome.setText("Home");
        mHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mHomeMouseClicked(evt);
            }
        });
        mHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(mHome);

        mEmployees.setText("Employees");
        mEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mEmployeesMouseClicked(evt);
            }
        });
        mEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeesActionPerformed(evt);
            }
        });
        jMenuBar1.add(mEmployees);

        mDepartments.setText("Departments");
        mDepartments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mDepartmentsMouseClicked(evt);
            }
        });
        jMenuBar1.add(mDepartments);

        mAssignments.setText("Assignments");
        mAssignments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mAssignmentsMouseClicked(evt);
            }
        });
        jMenuBar1.add(mAssignments);

        mPayroll.setText("Payroll");
        mPayroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mPayrollMouseClicked(evt);
            }
        });
        jMenuBar1.add(mPayroll);

        mClose.setText("Close");
        mClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mCloseMouseClicked(evt);
            }
        });
        mClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCloseActionPerformed(evt);
            }
        });
        jMenuBar1.add(mClose);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(134, 134, 134))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mHomeMouseClicked
        MainForm x = new MainForm();
        x.setVisible(true);
    }//GEN-LAST:event_mHomeMouseClicked

    private void mHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHomeActionPerformed
        
    }//GEN-LAST:event_mHomeActionPerformed

    private void mEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mEmployeesMouseClicked
        EmployeeForm x = new EmployeeForm();
        x.setVisible(true);
    }//GEN-LAST:event_mEmployeesMouseClicked

    private void mEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEmployeesActionPerformed
        EmployeeForm x = new EmployeeForm();
        x.setVisible(true);
    }//GEN-LAST:event_mEmployeesActionPerformed

    private void mDepartmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDepartmentsMouseClicked
        DepartmentForm x = new DepartmentForm();
        x.setVisible(true);
    }//GEN-LAST:event_mDepartmentsMouseClicked

    private void mAssignmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mAssignmentsMouseClicked
       
    }//GEN-LAST:event_mAssignmentsMouseClicked

    private void mCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mCloseMouseClicked
        dispose();
    }//GEN-LAST:event_mCloseMouseClicked

    private void mCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mCloseActionPerformed

    private void mPayrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mPayrollMouseClicked
        PayrollForm x = new PayrollForm();
        x.setVisible(true);
    }//GEN-LAST:event_mPayrollMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignmentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignmentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mAssignments;
    private javax.swing.JMenu mClose;
    private javax.swing.JMenu mDepartments;
    private javax.swing.JMenu mEmployees;
    private javax.swing.JMenu mHome;
    private javax.swing.JMenu mPayroll;
    // End of variables declaration//GEN-END:variables
}
