/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalexamproject;

/**
 *
 * @author Al
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mHome = new javax.swing.JMenu();
        mEmployees = new javax.swing.JMenu();
        mDepartments = new javax.swing.JMenu();
        mAssignments = new javax.swing.JMenu();
        mPayroll = new javax.swing.JMenu();
        mClose = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 204));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Jamming Jelly preserves contain only natural ingredients, without artifical flavors, preservatives, or coloring; and guarantees high quality products with consistent results.\n\nJamming Jelly offers a range of flavors of Premium Preserves, Bakery Jams, and Glaes for use in Bakery, Retail, and Foodservice operations.\n\nJamming Jelly uses 70% fruit preserves from the famous Lake Lucerne Orchards in Switzerland. These products are available in Tubs, Jars, and Portions, Bakery Jams, Gels, and Glazes - all in a variety of flavors and sizes.\n\nCarefully selected fruits, premium packaging, and a unique cooking method are what makes Jamming Jelly products so special.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jMenuBar1.setBackground(new java.awt.Color(51, 0, 204));
        jMenuBar1.setForeground(new java.awt.Color(255, 153, 153));

        mHome.setText("Home");
        mHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mHomeMouseClicked(evt);
            }
        });
        mHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(mHome);

        mEmployees.setText("Employees");
        mEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mEmployeesMouseClicked(evt);
            }
        });
        mEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEmployeesActionPerformed(evt);
            }
        });
        jMenuBar1.add(mEmployees);

        mDepartments.setText("Departments");
        mDepartments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mDepartmentsMouseClicked(evt);
            }
        });
        jMenuBar1.add(mDepartments);

        mAssignments.setText("Assignments");
        mAssignments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mAssignmentsMouseClicked(evt);
            }
        });
        jMenuBar1.add(mAssignments);

        mPayroll.setText("Payroll");
        mPayroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mPayrollMouseClicked(evt);
            }
        });
        jMenuBar1.add(mPayroll);

        mClose.setText("Close");
        mClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mCloseMouseClicked(evt);
            }
        });
        mClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCloseActionPerformed(evt);
            }
        });
        jMenuBar1.add(mClose);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(125, 125, 125)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHomeActionPerformed
        
       
    }//GEN-LAST:event_mHomeActionPerformed

    private void mCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCloseActionPerformed
       dispose();
    }//GEN-LAST:event_mCloseActionPerformed

    private void mEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEmployeesActionPerformed
         EmployeeForm x = new EmployeeForm();
         x.setVisible(true);
         
    }//GEN-LAST:event_mEmployeesActionPerformed

    private void mEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mEmployeesMouseClicked
         EmployeeForm x = new EmployeeForm();
         x.setVisible(true);       
    }//GEN-LAST:event_mEmployeesMouseClicked

    private void mDepartmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDepartmentsMouseClicked
        DepartmentForm x = new DepartmentForm();
        x.setVisible(true);
    }//GEN-LAST:event_mDepartmentsMouseClicked

    private void mAssignmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mAssignmentsMouseClicked
        AssignmentForm x = new AssignmentForm();
        x.setVisible(true);
    }//GEN-LAST:event_mAssignmentsMouseClicked

    private void mHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mHomeMouseClicked
        
    }//GEN-LAST:event_mHomeMouseClicked

    private void mCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mCloseMouseClicked
        dispose();
    }//GEN-LAST:event_mCloseMouseClicked

    private void mPayrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mPayrollMouseClicked
        PayrollForm x = new PayrollForm();
        x.setVisible(true);
    }//GEN-LAST:event_mPayrollMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu mAssignments;
    private javax.swing.JMenu mClose;
    private javax.swing.JMenu mDepartments;
    private javax.swing.JMenu mEmployees;
    private javax.swing.JMenu mHome;
    private javax.swing.JMenu mPayroll;
    // End of variables declaration//GEN-END:variables
}
